### ISSUE TITLE
Recommend an introduction

### ISSUE THREAD

**Issue by wpzdm** [prathyvsh/category-theory-resources#4]
Category Theory: A Gentle Introduction. by Peter Smith
https://www.logicmatters.net/resources/pdfs/GentleIntro.pdf

This is a work-in-progress, and I did not read it except for a few pages. But Prof. Smith is a recognized author in math logic, and I like his website a lot. 

The following link might also be useful: https://www.logicmatters.net/categories/

**Comment by prathyvsh** [comment]
Hey there, thanks for the recommendation. I had come across it a while ago and thought I had mentioned it in the under consideration section, but I see that I hadn't. Thank you for the recommendation. I do love the work of Peter Smith!
